version: '3.5'

volumes:
  postgres-data:
  elasticsearch-data:
  s3-data:

services:
  postgres:
    image: "postgres@sha256:f4603c7b8aaf418393edb8cd5e2d1abd91d686ab571302dc83f887ea4a56286b"
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $USER

  elasticsearch:
    image: "elasticsearch:6.8.9"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  nginx:
    image: "nginx:1.14-alpine"
    ports:
      - "80:80"
    volumes:
      - "./dmrunner-nginx/nginx.conf:/etc/nginx/nginx.conf:ro"

  s3:
    image: "localstack/localstack@sha256:cb08eabae40fa1e33babffa4ff8c454c2276405cfc2fe1e2e300e5625244bdf7"
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack
      - DEFAULT_REGION=eu-west-1
      - EXTERNAL_HOSTNAME=localhost/assets
    volumes:
      - "s3-data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
